[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello_anchor = "CGHSJqE8WD56Yysm2s9MAh53kJcpa2bTWqegtMvqgpNN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
